(let ((input "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"))
  (let ((l-a 0) (l-c 0) (l-g 0) (l-t 0))
    (dotimes (i (length input))
      (case (aref input i)
        (#\A (incf l-a))
        (#\C (incf l-c))
        (#\G (incf l-g))
        (#\T (incf l-t))))
    (format t "~a ~a ~a ~a~%" l-a l-c l-g l-t)
    `(,l-a ,l-c ,l-g ,l-t)))